# Generated by Django 6.0.3 on 2026-04-07 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10, unique=True)),
                ('semester', models.CharField(max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posting_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('personal_details', models.TextField()),
                ('image', models.ImageField(upload_to='student_images/')),
                ('duration', models.CharField(max_length=50)),
                ('food', models.BooleanField(default=False)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_contact', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(max_length=254)),
                ('proctor_name', models.CharField(max_length=100)),
                ('proctor_contact', models.CharField(max_length=20)),
                ('hostel_incharge_name', models.CharField(max_length=100)),
                ('hostel_incharge_contact', models.CharField(max_length=20)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_app.course')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_app.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date_out', models.DateTimeField()),
                ('date_in', models.DateTimeField()),
                ('parent_permission', models.BooleanField(default=False)),
                ('proctor_permission', models.BooleanField(default=False)),
                ('incharge_permission', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.student')),
            ],
        ),
    ]
