# Generated by Django 5.2.5 on 2026-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_alter_course_id_alter_permission_id_alter_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
